peer2anonet: made security enhancements for input data

diff --git a/contrib/peer2anonet/peer2anonet b/contrib/peer2anonet/peer2anonet
--- a/contrib/peer2anonet/peer2anonet
+++ b/contrib/peer2anonet/peer2anonet
@@ -40,7 +40,7 @@ read -p "Enter your peer asn: " PEERASN
 # Do some security checks on variables:
 TEST[0]=$PEERNAME; TEST[1]=$YOURNET; TEST[2]=$YOURROUTE; TEST[3]=$YOURIP
 TEST[4]=$REMOTEIP; TEST[5]=$PEERIP; TEST[6]=$YOURPORT; TEST[7]=$PEERPORT
-       TEST[8]=$YOURASN; TEST[9]=$PEERASN; TEST[10]=$PUBKEY
+       TEST[8]=$YOURASN; TEST[9]=$PEERASN;
 
 for((X=0;X<=5;X++)); do
 if [[ $(echo ${TEST[$X]} | tr -d 'a-zA-Z0-9._-' | wc -c) -gt 1 ]]; then
@@ -53,7 +53,7 @@ done
 
 for((X=6;X<=9;X++)); do
 if [[ $(echo ${TEST[$X]} | tr -d '0-9' | wc -c) -gt 1 ]]; then
- echo "peer2anonet: fatal error: unacceptable data:$X ${TEST[$X]}
+ echo "peer2anonet: fatal error: unacceptable data: ${TEST[$X]}
 "
  exit 1
 fi
@@ -159,7 +159,13 @@ ln -s /services/"$PEERNAME" /service/
 echo "peer2anonet: New peering session configured
 "
 read -p "Enter your peer's public key: " PUBKEY
+if [[ $(echo "$PUBKEY" | tr -d 'a-zA-Z0-9' | wc -c) -gt 1 ]]; then
+ echo "peer2anonet: fatal error: unacceptable data: $PUBKEY
+"
+ exit 1
+fi
 echo "$PUBKEY" > /services/"$PEERNAME"/pubkey
+
 exit 0
 
 
